Application - Make Experience step fully functional
GCTC-NTGC/TalentCloud pull request #4341
Opened 2020-09-02 18:36 UTC by tristan-orourke

Resolves #2860.

Blocked by #4334. 

### Notes:
- The handleSubmit function is quite complicated, because the API call is different depending on whether a new Experience must be created or an existing one must be updated, and because each ExperienceSkill object must be created/deleted with an individual API request. This could be simplified, but would require more work on the backend.

2020-09-16 13:10 UTC, yonikid15 requested changes
Looks good so far 👍 Just a couple issues: 
- The experience skills aren't getting added to the db. 
- I made a fix for a mistake I made on the Experience component when displaying contants on a couple of the accordions (education and award).

2020-09-16 17:21 UTC, tristan-orourke commented on resources/assets/js/components/Checkbox.tsx
> +          <label>
Yeah, and the htmlFor caused more issues when there were non-unique ids on the page. Obviously we should avoid non-unique ids anyway, but I don't think there's a downside to removing this.

2020-09-16 20:22 UTC, tristan-orourke commented
Regarding how the experience constants were showing up in experience accordions, good catch that things weren't working. 
Chris and I were planning on a different solution, where we add the text of the constants directly in the Experience api responses, and then we can simply use them on the frontend. 
So I'm going to complete those API response and then revert 062671b44cbd448bdb98ca982c08879320c464ff .

2020-09-16 20:57 UTC, tristan-orourke commented on resources/assets/js/components/Application/Experience/ExperiencePage.tsx
> +        jobClassificationId={job?.classification_id ?? 1}
I've added a loading state for when job isn't loading yet, and I've allowed the code to gracefully handle classification_id being null, though that should never be the case for a published job poster.

2020-09-18 20:10 UTC, yonikid15 reviewed
Looks good, good job 👍  
Just one thing. The modal forms need to be reset after submission `actions.resetForm()`.
Also, we need to fix the focus issue on the CheckboxField component, then merge that branch first.

2020-09-21 17:39 UTC, Khristophor commented
@tristan-orourke `JobWorkEnv.test.tsx` snapshot and `Job Poster Builder - New Job` Testcafe test need updating, and then this should be good to go

2020-09-21 19:35 UTC, yonikid15 approved these changes

2020-09-21 19:47 UTC, merged