Application Review step fully functional
GCTC-NTGC/TalentCloud pull request #4422
Opened 2020-09-23 21:39 UTC by tristan-orourke

Resolves #2891.

### Notes:
- Like other Application steps, this now triggers fetching of all Application data (if its not yet in Redux store).
- The Save and ____ buttons now save the 'share with manager' field of the application.
- This PR also adds the data fetching to the Welcome step of the Application.

2020-09-24 14:04 UTC, Khristophor requested changes
Looks good, just a couple failing unit tests to fix up

2020-09-24 14:57 UTC, tristan-orourke commented on resources/assets/js/hooks/applicationHooks.tsx
> +      setApplicationFetched(true);
Yes, this prevents more dispatches after a failure. Can you think of any obvious conditions where we'd want to retry?

2020-09-24 14:59 UTC, tristan-orourke commented on resources/assets/js/components/Application/Review/ReviewPage.tsx
> +      user !== null ? (
It does, but typescript can't seem to infer that. Without the additional conditions, TypeScript throws compile errors. :(

2020-09-24 15:02 UTC, Khristophor commented on resources/assets/js/components/Application/Review/ReviewPage.tsx
> +      user !== null ? (
😭

2020-09-24 15:10 UTC, Khristophor commented on resources/assets/js/hooks/applicationHooks.tsx
> +      setApplicationFetched(true);
I was just thinking it feels weird that if it attempts one fetch, and it doesn't resolve, there's no real way for a user to reattempt aside from a full refresh. Maybe it's just a messaging thing we could improve on (Hey something went wrong try refreshing the page or coming back later).

Or if it's a timeout and not a 500/403/422, we could reattempt after a specific delay.

2020-09-24 21:21 UTC, tristan-orourke commented on resources/assets/js/hooks/applicationHooks.tsx
> +      setApplicationFetched(true);
You're right. I'm just not sure how to accomplish that right now without a substantial change to how we manage state and these requests.

2020-09-25 12:52 UTC, Khristophor approved these changes

2020-09-25 12:53 UTC, merged