Add translations for content on the new Application
GCTC-NTGC/TalentCloud pull request #4444
Opened 2020-09-29 21:11 UTC by tristan-orourke

Resolves #4442.

2020-11-04 19:02 UTC, yonikid15 requested changes

2020-11-04 19:02 UTC, yonikid15 commented on etc/scripts/replace_fr_translations.py
> +
Good stuff. Is there a way for me to test this locally?

2020-11-05 19:33 UTC, yonikid15 commented on resources/assets/js/components/Application/Intro/Intro.tsx
>                bold: (...chunks): React.ReactElement => (
Still need to change `bold:` to `b:` in the values prop on line 59. 😅

2020-11-05 19:50 UTC, tristan-orourke commented on resources/assets/js/components/Application/Intro/Intro.tsx
>                bold: (...chunks): React.ReactElement => (
Oops

2020-11-05 19:52 UTC, yonikid15 approved these changes

2020-11-05 20:11 UTC, merged