Task/depreciate existing profile pages
GCTC-NTGC/TalentCloud pull request #4448
Opened 2020-09-30 14:22 UTC by jaysonmc

Resolves #4077

### Notes:
- Still missing the icon that was in the mockup provided in the issue
- Used a <br /> tag at the bottom of the archived.html.twig file, which is suboptimal. Ideally formatting could be used to fix this, though formatting seems to be different on different pages and the tb tag doesn't seem to provide the proper space (as expected). Ideally this could be fixed prior to merging

2020-09-30 20:49 UTC, tristan-orourke requested changes
We'll need to turn the "Read more" line in the alert into a link (or remove it), but I'm waiting on a decision for where it should link to.
In the meantime, we should also disable the Delete and Save buttons (and Add Work Sample/Skill/Project buttons) that appear within the accordions for existing resources. I think these are in the following twig files:
- common/skills
- common/relatives
- common/reference
- common/relatives-projects
- common/sample

2020-09-30 20:50 UTC, jaysonmc commented on resources/views/applicant/profile/archived.html.twig
> +                    <p data-c-color="c3" data-c-margin="top(.5)"><u>{{archived.page_going_away_read_more}}</u></p>
Oh, that is a good point. Yes, it should be.

Aye, if we get the link I can throw it in.

Good catch :)

2020-10-01 15:44 UTC, jaysonmc commented on resources/views/applicant/profile/archived.html.twig
> +                    <p data-c-color="c3" data-c-margin="top(.5)"><u>{{archived.page_going_away_read_more}}</u></p>
Regarding the missing disabled buttons, should be completed as of https://github.com/GCTC-NTGC/TalentCloud/pull/4448/commits/4585687131335318c30f02cfc8aebaeb17a12e78

Link (and icon) still pending

2020-10-05 20:12 UTC, tristan-orourke approved these changes

2020-10-06 13:57 UTC, merged