Add partner, host fields to Department
GCTC-NTGC/TalentCloud pull request #4592
Opened 2020-10-27 18:36 UTC by mnigh

Resolves #2133

2020-10-29 15:24 UTC, Khristophor requested changes

2020-10-29 15:24 UTC, Khristophor commented on app/Http/Controllers/Admin/DepartmentCrudController.php
> +                'label'=> 'Department Partners'
Pedantic change, but we refer to them as "Partner Departments"

2020-10-30 14:55 UTC, Khristophor approved these changes
Looks good. We'll need to make sure people are aware that Departments need to be tagged and ordered correctly when this change is deployed in order to have the FAQ page display the correct info.

2020-10-30 15:43 UTC, mnigh commented
> Looks good. We'll need to make sure people are aware that Departments need to be tagged and ordered correctly when this change is deployed in order to have the FAQ page display the correct info.

@Khristophor Indeed, is there a formal place to put these instructions for a post-release?

2020-10-30 15:45 UTC, Khristophor commented
> > Looks good. We'll need to make sure people are aware that Departments need to be tagged and ordered correctly when this change is deployed in order to have the FAQ page display the correct info.
> 
> @Khristophor Indeed, is there a formal place to put these instructions for a post-release?

Good question. @gobyrne do we have anywhere (aside from Slack) to notify people about things like this before/after deployment?

2020-11-05 19:04 UTC, gobyrne commented
> > > Looks good. We'll need to make sure people are aware that Departments need to be tagged and ordered correctly when this change is deployed in order to have the FAQ page display the correct info.
> > 
> > 
> > @Khristophor Indeed, is there a formal place to put these instructions for a post-release?
> 
> Good question. @gobyrne do we have anywhere (aside from Slack) to notify people about things like this before/after deployment?

If you are just notifying, slack seems appropriate. Is there something else we need?

2020-11-05 19:17 UTC, tristan-orourke commented
We don't have a good way of reminding _ourselves_ that something needs to be done when we deploy. Maybe adding a note in `deploy-instructions.tsx`? I always double check that file before deploying.

2020-11-05 20:59 UTC, mnigh commented
> Maybe adding a note in `deploy-instructions.tsx`?
@tristan-orourke that would make sense if it was an instruction that was recurring and therefore going to be committed to the repository, whereas this case is a one off action that is required. is there somewhere in comments or notes for the next release that would be suited for this case?

2020-11-06 13:33 UTC, Khristophor commented
> > Maybe adding a note in `deploy-instructions.tsx`?
> 
> @tristan-orourke that would make sense if it was an instruction that was recurring and therefore going to be committed to the repository, whereas this case is a one off action that is required. is there somewhere in comments or notes for the next release that would be suited for this case?

We don't have a changelog or similar, so it might make sense to put in the deploy-instructions file as a `this release only` note and remove in the future. @tristan-orourke ?

2020-11-06 15:44 UTC, tristan-orourke commented
> We don't have a changelog or similar, so it might make sense to put in the deploy-instructions file as a `this release only` note and remove in the future. @tristan-orourke ?

@Khristophor Yeah, that's what I was thinking. I don't think there's a better place that we're used to checking, unfortunately.

We do use github to build a changelog from all the PRs that have been merged since last release, but its going to be reaaaally long, and we're not in the habit of looking through it before deployment.

2020-11-09 16:18 UTC, mnigh commented
@tristan-orourke I have added some temporary instructions to the [deploy-instructions.txt file](https://github.com/GCTC-NTGC/TalentCloud/pull/4592/commits/64e9f7378ae5a05ad05f24e7bf520ee9ad3728e5). If this is clear enough, please feel free to merge this into the dev branch, thanks.

2020-11-10 15:17 UTC, merged