Create Skills, Skills Category relationship table
GCTC-NTGC/TalentCloud pull request #4789
Opened 2020-11-24 16:10 UTC by mnigh

Resolves #4691

### Notes:
- Requires #4772 to be merged first.

2020-12-04 21:50 UTC, tristan-orourke reviewed
Looks good; waiting on the other PRs.

2020-12-07 20:27 UTC, tristan-orourke requested changes

2020-12-07 20:27 UTC, tristan-orourke commented on database/migrations/2020_11_24_150537_create_skill_categories_skills_table.php
> +        Schema::create('skill_categories_skills', function (Blueprint $table) {
Accordion to Laravel [pivot table naming convention conenvtion](https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-table-structure), this table should be called `skill_skill_category`.

2020-12-07 20:27 UTC, tristan-orourke commented on app/Models/Skill.php
> +    public function skill_categories() // phpcs:ignore
Should add the relationship to the class docblock.

2020-12-07 21:22 UTC, mnigh commented
Code coverage test fails arbitrary coverage drop allowed for success value, 2.5%, by 0.06% (2.56%).

2020-12-08 15:27 UTC, tristan-orourke approved these changes

2020-12-08 17:26 UTC, merged