IE Banner and Dialog
GCTC-NTGC/TalentCloud pull request #4893
Opened 2020-12-07 16:40 UTC by bitliege

Sets up static content for #4579

We'll want to ensure some of the discussion in the issue is addressed. Ping me if there are questions!

2020-12-07 17:34 UTC, mnigh commented on resources/views/common/h2-ie-dialog.html.twig
> +          <p data-h2-margin="b(tb, 1)">As <a href="" title="">Microsoft has begun phasing out support for Internet Explorer</a>, we recommend using Talent Cloud from a modern web browser for the best
@bitliege Should the `href` and `title` attributes in the `a` tag not have values or is this forthcoming?

2021-01-20 22:07 UTC, mnigh commented
@tristan-orourke We will need translations for [Internet Explorer Banner and Dialog Language Lines](https://github.com/GCTC-NTGC/TalentCloud/blob/4b1dcadce72d88983fb0d22893e430d6459a7bee/resources/lang/fr/common/internet_explorer.php).

2021-01-27 20:02 UTC, tristan-orourke requested changes

2021-01-27 20:05 UTC, tristan-orourke requested changes
I moved the script include, but its still not working. The banner does appear in IE, and not other browsers, but the "Learn more about this decision" button doesn't do anything, and the "Dismiss" button throws a console error: _Object doesn't support property or method 'remove'_

2021-01-28 00:59 UTC, mnigh commented
> I moved the script include, but its still not working. The banner does appear in IE, and not other browsers, but the "Learn more about this decision" button doesn't do anything, and the "Dismiss" button throws a console error: _Object doesn't support property or method 'remove'_

This works for me with a previous version of Hydrogen (v0.0.32). @bitliege: Is there anything that has changed with the Dialog component since v0.0.32?

When I switch out the version in the [twig template file](https://github.com/GCTC-NTGC/TalentCloud/blob/feature/ie-alert/resources/views/common/scripts.html.twig#L23) from the following, it works again:

https://cdn.jsdelivr.net/npm/@hydrogen-design-system/system@latest/dist/compiled/latest/system.min.js
to
https://cdn.jsdelivr.net/npm/@hydrogen-design-system/system@v0.0.32/dist/compiled/latest/system.min.js

For the route posted to on _Dismiss_, you may need to clear the route cache since **/api/v1/browser-message** is a new route: `php artisan route:clear` (macOS, not sure on Windows how to do this).

2021-01-28 01:02 UTC, mnigh commented on resources/assets/js/browserMessage.js
> +import { axios } from "./api/base";
@tristan-orourke I'm not entirely sure, but I did this based on the [alerts.js](https://github.com/GCTC-NTGC/TalentCloud/blob/feature/ie-alert/resources/assets/js/alerts.js#L1) that does the same thing with axios.

2021-01-28 16:15 UTC, tristan-orourke commented
Okay, with #e89645899ffbcda1934ad4587aeda2b7ec5b4fa9 the dismiss button now works.

I was going to suggest that we set the cookie directly in the `browserMessage.js` file, to avoid an extra request and fairly pointless api endpoint, but then I realized Laravel does some nice encryption for us that we may not want to skip.

2021-02-02 18:11 UTC, tristan-orourke commented on resources/assets/js/browserMessage.js
> +import { axios } from "./api/base";
Seems to work.

2021-02-02 18:12 UTC, tristan-orourke commented
I hate to suggest this now after so much work... but I now feel like we should just make the banner non-dismissible. We really don't expect the site to work in IE at this point. Thoughts? @mnigh @bitliege

2021-02-02 19:12 UTC, mnigh commented
> I hate to suggest this now after so much work... but I now feel like we should just make the banner non-dismissible. We really don't expect the site to work in IE at this point. Thoughts? @mnigh @bitliege

I agree. The purpose of the banner is to alert the user that the site that they are currently visiting will not work using the browser they are currently using: dismissing the banner won't change that fact and they should not continue using the site.

2021-02-10 14:43 UTC, mnigh commented
Resolves #4579.

2021-02-10 16:51 UTC, yonikid15 approved these changes
Nice work 👍 Just missed removing the goc and alert on one file. I had the branch open so I just did it quickly.

2021-02-10 17:18 UTC, yonikid15 approved these changes

2021-02-11 00:56 UTC, tristan-orourke approved these changes

2021-02-11 00:57 UTC, merged