Feature - Applicant Profile Skills UI
GCTC-NTGC/TalentCloud pull request #5087
Opened 2021-01-18 16:16 UTC by Khristophor

Relates to the bottom section of [the wireframes](https://xd.adobe.com/view/c2c5a303-1dcd-4436-bec3-eea0a3ca3523-9796/) for the profile skills.

2021-02-09 14:20 UTC, mnigh commented
Resolves #4858.

### Notes
Main list component, as well as child components, can be viewed as stories in storybook:
- Applicant Profile / Skills / List
- Applicant Profile / Skills / Accordion
- Applicant Profile / Skills / Accordion (No Experiences)
- Applicant Profile / Experience Details / Work
- Applicant Profile / Experience Details / Education
- Applicant Profile / Experience Details / Community
- Applicant Profile / Experience Details / Award
- Applicant Profile / Experience Details / Personal

2021-02-11 22:54 UTC, tristan-orourke requested changes
Nice work, looks great, works smoothly! Just needs a deleteSkill handler passed in and attached to the buttons.

2021-02-11 22:54 UTC, tristan-orourke commented on resources/assets/js/components/ApplicantProfile/Skills/Accordion.tsx
> +                        <Dialog.ActionBtn
Needs an onClick. The SkillAccordion should probably accept a callback prop, something like `deleteSkill: (skillId: number) => Promise<void>`, which can be called when you click this.

2021-02-11 22:54 UTC, tristan-orourke commented on resources/assets/js/components/ApplicantProfile/Skills/Accordion.tsx
> +                  <button
This also need the onClick deleteSkill.

2021-02-11 22:54 UTC, tristan-orourke commented on resources/assets/js/components/ApplicantProfile/Skills/List.tsx
> +  const skillCategoriesGroupedObject = skillCategories
This looks like a lot of iterating, it might be worth wrapping this in `useMemo`.

2021-02-11 23:01 UTC, tristan-orourke commented
@mnigh @bitliege I noticed a weird dialog bug in these stories. It probably has nothing to do with this PR but we should look into at some point. 
Some of the dialogs close correctly when I press escape, but for some of them the overlay disappears and the dialog remains until I click a close button. I'm not sure what the difference is.

2021-02-12 15:01 UTC, tristan-orourke commented on resources/assets/js/components/ApplicantProfile/Skills/List.tsx
> +      [],
With the way parent_id is used as a key, and accordion to the type attributed to accumulator, this should be an empty object `{}` not an array. I'm surprised TypeScript didn't warn about that 🤔

2021-02-12 15:12 UTC, tristan-orourke commented on resources/assets/js/components/ApplicantProfile/Skills/List.tsx
> +  const skillCategoriesGrouped = Object.keys(skillCategoriesGroupedObject).map(
I think you want filter instead of map here. Having entries of `false` in the resulting array isn't useful.

2021-02-12 15:28 UTC, tristan-orourke commented on resources/assets/js/components/ApplicantProfile/Skills/List.tsx
> +          <div key={category.catId}>
`catId` is actually undefined. It was never a property attached to elements, it was the key of that element (or index, when its an array). You could get the index like so:
```
skillCategoriesGrouped.map((category, i) => (
      <div key={i}>
```
But I don't think that is the best key to use.

2021-02-12 20:22 UTC, tristan-orourke approved these changes

2021-02-12 21:01 UTC, merged