Improve breadcrumbs on Application (for applicants)
GCTC-NTGC/TalentCloud pull request #5446
Opened 2021-03-16 18:41 UTC by tristan-orourke

Resolves #5368

2021-03-16 18:42 UTC, tristan-orourke commented
This was much easier when I remembered we already have the `custom_breadcrumbs` mechanic 😅

2021-03-17 14:17 UTC, mnigh requested changes
A few very small things to address, but otherwise (in honour of St. Patrick's Day), maith thú!

2021-03-17 14:17 UTC, mnigh commented on app/Http/Controllers/ApplicationTimelineController.php
> +                    'title' => $application->job_poster->title, // TODO: Check with design what the title should be.
Can the comment, `TODO: Check with design what the title should be.`,  be removed at this point?

2021-03-17 14:17 UTC, mnigh commented on app/Http/Controllers/ApplicationTimelineController.php
> +                    'title' => $application->job_poster->title, // TODO: Check with design what the title should be.
Can the comment, `TODO: Check with design what the title should be.`,  be removed at this point?

2021-03-17 14:17 UTC, mnigh commented on resources/lang/fr/common/breadcrumbs.php
> +    'application_id' => 'Application Id : :id',
Is _Application Id_ the FR translation of the EN _Application Id_? If not, this should be replaced with its FR version.

2021-03-17 16:46 UTC, tristan-orourke commented on resources/lang/fr/common/breadcrumbs.php
> +    'application_id' => 'Application Id : :id',
Its what I got from DeepL translate. I wanted to run it by the team at demo today.

2021-03-17 19:20 UTC, mnigh requested changes
Changing the value of the FR string uncovered an issue with [string formatting](https://github.com/GCTC-NTGC/TalentCloud/pull/5446/files#diff-763bb5a579199054b61beac459daae7c765a07906fcd6da4e4e9dff788973b15L11-L19) where it uses Twig's title filter to titlecase the value, which is not FR-friendly.

![Screen Shot 2021-03-17 at 15 09 23](https://user-images.githubusercontent.com/3046459/111524975-73c05b00-8733-11eb-998e-26f7c44c7d5f.png)

2021-03-19 15:48 UTC, mnigh approved these changes
👍

2021-03-19 15:52 UTC, merged