Bugfix - application timeline skills step save and quit function
GCTC-NTGC/TalentCloud pull request #5508
Opened 2021-03-25 16:40 UTC by yonikid15

Resolves #5352 

### Notes:
- Ensures user can save and quit skills step without forcing them to fill out all the justifications.
- If they select "Save and Quit" and none of the forms have been filled it will simply jump to applications page.
- If they select "Save and Quit" and they have changed some or all of the forms. It will save all the forms that pass validation (not empty) and then go to the applications page. 
- One thing that may or may not be a problem is since you are leaving the page without saving it triggers `<AlertWhenSaved>`, which causes the confirmation alert to popup.

2021-04-01 21:39 UTC, tristan-orourke requested changes
If you press save and quit, and you have one or more invalid (ie empty) forms, none of them will be saved. I think you still want the valid ones to be saved?

2021-04-08 14:23 UTC, yonikid15 commented
> If you press save and quit, and you have one or more invalid (ie empty) forms, none of them will be saved. I think you still want the valid ones to be saved?

Nice catch, currently trying to fix this now. It's a little trickier then I thought.

2021-04-09 16:42 UTC, tristan-orourke approved these changes
The way the "Are you sure you want to leave?" dialog appears even if every _valid_ form has been saved is a little annoying, but its not _entirely_ unreasonable, so whatever. Your changes look good!

2021-04-09 16:42 UTC, tristan-orourke commented on resources/assets/js/components/Application/Skills/Skills.tsx
> +import { isEmpty } from "lodash";
Remember, since lodash is a big library it allows you to import more efficiently by doing `import isEmpty from "lodash/isEmpty"`

2021-04-09 16:42 UTC, tristan-orourke commented on resources/assets/js/components/Application/Skills/Skills.tsx
> +import { isEmpty } from "lodash";
Actually its not being used, I'll just delete it :P

2021-04-09 17:02 UTC, merged